name: WxJava:branch-2
on:
  pull_request:
    branches:
      branch-2
  push:
    branches:
      - branch-2
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.maven-
          key: ${{ runner.os }}-maven
      - name: build with maven-
        uses: actions/setup-java@4
        with:
          java-version: ${{ matrix.java }} 
      - uses: actions/checkout@4
      - run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true        
