on:
  push:
    branches:
      - develop      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up OpenJDK8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean package -DskipTests=true -Dcheckstyle.skip=true
    - name: Cache .m2 repository
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-m2-repository
        path: $HOME/.m2/repository
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        connection_url: <connection_url>
        server_address: <address>
        server_port: 465
        subject: <subject>
        to: <email>@<email>.<email>
        from: Placeholder
        body: Build job of ${{github.repository}} finished with status ${{job.status}}
